export CUDA_VISIBLE_DEVICES=0
model_name=TimesMR
temporal_function='down'


python3 -u run.py \
    --task_name long_term_forecast \
    --is_training 1 \
    --root_path ./dataset/METR \
    --data_path METR-LA.csv \
    --model_id METR-LA_96_96 \
    --model $model_name \
    --data custom \
    --features M \
    --freq t \
    --seq_len 96 \
    --label_len 96 \
    --pred_len 12 \
    --e_layers 2 \
    --temporal_function $temporal_function\
    --d_layers 1 \
    --factor 3 \
    --dropout 0.3 \
    --d_model 512 \
    --d_ff 512 \
    --learning_rate 0.001 \
    --n_patch -1 \
    --enc_in 207 \
    --dec_in 207 \
    --c_out 207 \
    --des 'Exp' \
    --lradj type1 \
    --patience 5 \
    --batch_size 32 \
    --itr 1 \
    --train_epochs 15 \
    --use_norm 0

python3 -u run.py \
    --task_name long_term_forecast \
    --is_training 1 \
    --root_path ./dataset/METR \
    --data_path METR-LA.csv \
    --model_id METR-LA_96_96 \
    --model $model_name \
    --data custom \
    --features M \
    --freq t \
    --seq_len 96 \
    --label_len 96 \
    --pred_len 24 \
    --e_layers 2 \
    --temporal_function $temporal_function\
    --d_layers 1 \
    --factor 3 \
    --dropout 0.3 \
    --d_model 512 \
    --d_ff 512 \
    --learning_rate 0.001 \
    --n_patch -1 \
    --enc_in 207 \
    --dec_in 207 \
    --c_out 207 \
    --des 'Exp' \
    --lradj type1 \
    --patience 5 \
    --batch_size 32 \
    --itr 1 \
    --train_epochs 15 \
    --use_norm 0

python3 -u run.py \
    --task_name long_term_forecast \
    --is_training 1 \
    --root_path ./dataset/METR \
    --data_path METR-LA.csv \
    --model_id METR-LA_96_96 \
    --model $model_name \
    --data custom \
    --features M \
    --freq t \
    --seq_len 96 \
    --label_len 96 \
    --pred_len 48 \
    --e_layers 2 \
    --temporal_function $temporal_function\
    --d_layers 1 \
    --factor 3 \
    --dropout 0.3 \
    --d_model 512 \
    --d_ff 512 \
    --learning_rate 0.001 \
    --n_patch -1 \
    --enc_in 207 \
    --dec_in 207 \
    --c_out 207 \
    --des 'Exp' \
    --lradj type1 \
    --patience 5 \
    --batch_size 32 \
    --itr 1 \
    --train_epochs 15 \
    --use_norm 0

python3 -u run.py \
    --task_name long_term_forecast \
    --is_training 1 \
    --root_path ./dataset/METR \
    --data_path METR-LA.csv \
    --model_id METR-LA_96_96 \
    --model $model_name \
    --data custom \
    --features M \
    --freq t \
    --seq_len 96 \
    --label_len 96 \
    --pred_len 96 \
    --e_layers 2 \
    --temporal_function $temporal_function\
    --d_layers 1 \
    --factor 3 \
    --dropout 0.3 \
    --d_model 512 \
    --d_ff 512 \
    --learning_rate 0.001 \
    --n_patch -1 \
    --enc_in 207 \
    --dec_in 207 \
    --c_out 207 \
    --des 'Exp' \
    --lradj type1 \
    --patience 5 \
    --batch_size 32 \
    --itr 1 \
    --train_epochs 15 \
    --use_norm 0
