export CUDA_VISIBLE_DEVICES=0
model_name=TimesMR

temporal_function='patch'

python3 -u run.py \
    --task_name long_term_forecast \
    --is_training 1 \
    --root_path ./dataset/exchange_rate/ \
    --data_path exchange_rate.csv \
    --model_id Exchange_96_96 \
    --model $model_name \
    --data custom \
    --features M \
    --freq d \
    --seq_len 96 \
    --label_len 48 \
    --pred_len 96 \
    --e_layers 2 \
    --temporal_function $temporal_function\
    --d_layers 1 \
    --factor 3 \
    --dropout 0.8 \
    --learning_rate 0.0001 \
    --n_patch -1 \
    --d_model 512 \
    --d_ff 2048 \
    --enc_in 8 \
    --dec_in 8 \
    --c_out 8 \
    --des 'Exp' \
    --itr 1 \
    --train_epochs 15 \
    --use_norm 1

python3 -u run.py \
    --task_name long_term_forecast \
    --is_training 1 \
    --root_path ./dataset/exchange_rate/ \
    --data_path exchange_rate.csv \
    --model_id Exchange_96_96 \
    --model $model_name \
    --data custom \
    --features M \
    --freq d \
    --seq_len 96 \
    --label_len 48 \
    --pred_len 192 \
    --e_layers 2 \
    --temporal_function $temporal_function\
    --d_layers 1 \
    --factor 3 \
    --dropout 0.8 \
    --learning_rate 0.0001 \
    --n_patch -1 \
    --d_model 512 \
    --d_ff 2048 \
    --enc_in 8 \
    --dec_in 8 \
    --c_out 8 \
    --des 'Exp' \
    --itr 1 \
    --train_epochs 15 \
    --use_norm 1

python3 -u run.py \
    --task_name long_term_forecast \
    --is_training 1 \
    --root_path ./dataset/exchange_rate/ \
    --data_path exchange_rate.csv \
    --model_id Exchange_96_96 \
    --model $model_name \
    --data custom \
    --features M \
    --freq d \
    --seq_len 96 \
    --label_len 48 \
    --pred_len 336 \
    --e_layers 2 \
    --temporal_function $temporal_function\
    --d_layers 1 \
    --factor 3 \
    --dropout 0.8 \
    --learning_rate 0.0001 \
    --n_patch -1 \
    --d_model 512 \
    --d_ff 2048 \
    --enc_in 8 \
    --dec_in 8 \
    --c_out 8 \
    --des 'Exp' \
    --itr 1 \
    --train_epochs 15 \
    --use_norm 1

python3 -u run.py \
    --task_name long_term_forecast \
    --is_training 1 \
    --root_path ./dataset/exchange_rate/ \
    --data_path exchange_rate.csv \
    --model_id Exchange_96_96 \
    --model $model_name \
    --data custom \
    --features M \
    --freq d \
    --seq_len 96 \
    --label_len 48 \
    --pred_len 720 \
    --e_layers 2 \
    --temporal_function $temporal_function\
    --d_layers 1 \
    --factor 3 \
    --dropout 0.8 \
    --learning_rate 0.0001 \
    --n_patch -1 \
    --d_model 512 \
    --d_ff 2048 \
    --enc_in 8 \
    --dec_in 8 \
    --c_out 8 \
    --des 'Exp' \
    --itr 1 \
    --train_epochs 15 \
    --use_norm 1